### PR TITLE
Trigger exceptions and crashes with buttons/Minor UI revamp

### LINKED ISSUE #4: Trigger exceptions and crashes with buttons instead of key combinations
We want to demonstrate the com.bugsplat.unity integration better on mobile. In order to make it easier to generate sample reports, we should display buttons that the user can click instead of triggering exceptions via key combinations.

### PR DESCRIPTION
**Pull request by Zoolouie**
This PR:
- Fixes #4 
- Adds button functionality over key combination functionality for mobile ease of use
- Lovingly repositions the BugSplat cube to really bring out it's best side

### CODE REVIEW

File: Assets/Scripts/BugSplatCube.cs [hunk 1]
```diff
@@ -0,0 +1,10 @@
+using UnityEngine;
+
+public class BugSplatCube : MonoBehaviour
+{
+    void Update()
+    {
+        // Rotate slowly, but menacingly
```
Comment (bobbyg603) [inline Assets/Scripts/BugSplatCube.cs:7]: 🤣

File: Packages/manifest.json [hunk 2]
```diff
@@ -1,16 +1,14 @@
...
-    "com.unity.timeline": "1.5.6",
-    "com.unity.toolchain.macos-x86_64-linux-x86_64": "0.1.21-preview",
-    "com.unity.toolchain.win-x86_64-linux-x86_64": "0.1.19-preview",
+    "com.unity.test-framework": "1.1.24",
+    "com.unity.textmeshpro": "3.0.4",
+    "com.unity.timeline": "1.5.4",
     "com.unity.ugui": "1.0.0",
-    "com.unity.visualscripting": "1.6.1",
+    "com.unity.visualscripting": "1.5.2",
     "com.unity.modules.ai": "1.0.0",
```
Comment (bobbyg603) [inline Packages/manifest.json:12]: Whoops, i think we might want to revert these changes

File: Packages/packages-lock.json [hunk 3]
```diff
@@ -7,12 +7,10 @@
       "dependencies": {}
     },
     "com.unity.collab-proxy": {
```
Comment (bobbyg603) [inline Packages/packages-lock.json:9]: Same here, i think we lose a few packages with these changes

**Review by bobbyg603 — APPROVED** [review]

**Comment by bobbyg603** [comment]
I will fix package versions on the main branch

**Comment by bobbyg603** [comment]
Great work @Zoolouie!!! Thanks for the PR 🚀🎉🍻
